# 한국의 서울의 대기 오염 측정 데이터

이 데이터는 6개 오염물질(SO2, NO2, CO, O3, PM10, PM2.5)에 대한 평균값을 제공한다.
2017~2019년 사이 매시간 서울 25개구의 데이터가 측정됐다.
이 데이터 세트는 네 개의 파일로 나뉜다.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## 데이터 1) Measurement info: 대기오염 측정 정보

1시간 평균 측정 제공

0: Normal
    
1: Need for calibration
    
2: Abnormal

4: Power cut off #전원차단
    
8: Under repair
    
9: abnormal data

In [2]:
df_info = pd.read_csv('C:/jupyter notebook/data/Measurement_info.csv',encoding='cp949')

In [3]:
df_info.shape

(3885066, 5)

In [4]:
df_info.head()

   Measurement date  Station code  Item code  Average value  Instrument status
0  2017-01-01 00:00           101          1          0.004                  0
1  2017-01-01 00:00           101          3          0.059                  0
2  2017-01-01 00:00           101          5          1.200                  0
3  2017-01-01 00:00           101          6          0.002                  0
4  2017-01-01 00:00           101          8         73.000                  0

In [5]:
df_info.tail()

,Measurement date,Station code,Item code,Average value,Instrument status
3885061,2019-12-31 23:00,123,9,13.000,0
3885062,2019-12-31 23:00,118,9,24.000,0
3885063,2019-12-31 23:00,105,8,19.000,0
3885064,2019-12-31 23:00,125,3,0.037,0
3885065,2019-12-31 23:00,108,3,0.030,0

## 데이터 2) easurement item info:대기오염 측정항목 정보

In [25]:
df_item = pd.read_csv('C:/jupyter notebook/data/Measurement_item_info.csv',encoding='cp949')

In [7]:
df.head(10)

,Item code,Item name,Unit of measurement,Good(Blue),Normal(Green),Bad(Yellow),Very bad(Red)
0,1,SO2,ppm,0.02,0.05,0.15,1.0
1,3,NO2,ppm,0.03,0.06,0.20,2.0
2,5,CO,ppm,2.00,9.00,15.00,50.0
3,6,O3,ppm,0.03,0.09,0.15,0.5
4,8,PM10,Mircrogram/m3,30.00,80.00,150.00,600.0
5,9,PM2.5,Mircrogram/m3,15.00,35.00,75.00,500.0

## 데이터 3) Measurement station info: 대기오염 계측소 정보

In [8]:
df_station = pd.read_csv('C:/jupyter notebook/data/Measurement_station_info.csv',encoding='cp949')

In [9]:
df_station.shape

(25, 5)

In [10]:
df_station.head(30)

,Station code,Station name(district),Address,Latitude,Longitude
0,101,Jongno-gu,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005008
1,102,Jung-gu,"15, Deoksugung-gil, Jung-gu, Seoul, Republic o...",37.564263,126.974676
2,103,Yongsan-gu,"136, Hannam-daero, Yongsan-gu, Seoul, Republic...",37.540033,127.004850
3,104,Eunpyeong-gu,"215, Jinheung-ro, Eunpyeong-gu, Seoul, Republi...",37.609823,126.934848
4,105,Seodaemun-gu,"32, Segeomjeong-ro 4-gil, Seodaemun-gu, Seoul,...",37.593742,126.949679
5,106,Mapo-gu,"10, Poeun-ro 6-gil, Mapo-gu, Seoul, Republic o...",37.555580,126.905597
6,107,Seongdong-gu,"18, Ttukseom-ro 3-gil, Seongdong-gu, Seoul, Re...",37.541864,127.049659
7,108,Gwangjin-gu,"571, Gwangnaru-ro, Gwangjin-gu, Seoul, Republi...",37.547180,127.092493
8,109,Dongdaemun-gu,"43, Cheonho-daero 13-gil, Dongdaemun-gu, Seoul...",37.575743,127.028885
9,110,Jungnang-gu,"369, Yongmasan-ro, Jungnang-gu, Seoul, Republi...",37.584848,127.094023
10,111,Seongbuk-gu,"70, Samyang-ro 2-gil, Seongbuk-gu, Seoul, Repu...",37.606719,127.027279
11,112,Gangbuk-gu,"49, Samyang-ro 139-gil, Gangbuk-gu, Seoul, Rep...",37.647930,127.011952
12,113,Dobong-gu,"34, Sirubong-ro 2-gil, Dobong-gu, Seoul, Repub...",37.654192,127.029088
13,114,Nowon-gu,"17, Sanggye-ro 23-gil, Nowon-gu, Seoul, Republ...",37.658774,127.068505
14,115,Yangcheon-gu,"56, Jungang-ro 52-gil, Yangcheon-gu, Seoul, Re...",37.525939,126.856603
15,116,Gangseo-gu,"71, Gangseo-ro 45da-gil, Gangseo-gu, Seoul, Re...",37.544640,126.835151
16,117,Guro-gu,"45, Gamasan-ro 27-gil, Guro-gu, Seoul, Republi...",37.498498,126.889692
17,118,Geumcheon-gu,"20, Geumha-ro 21-gil, Geumcheon-gu, Seoul, Rep...",37.452357,126.908296
18,119,Yeongdeungpo-gu,"11, Yangsan-ro 23-gil, Yeongdeungpo-gu, Seoul,...",37.525007,126.897370
19,120,Dongjak-gu,"6, Sadang-ro 16a-gil, Dongjak-gu, Seoul, Repub...",37.480917,126.971481
20,121,Gwanak-gu,"14, Sillimdong-gil, Gwanak-gu, Seoul, Republic...",37.487355,126.927102
21,122,Seocho-gu,"16, Sinbanpo-ro 15-gil, Seocho-gu, Seoul, Repu...",37.504547,126.994458
22,123,Gangnam-gu,"426, Hakdong-ro, Gangnam-gu, Seoul, Republic o...",37.517528,127.047470
23,124,Songpa-gu,"236, Baekjegobun-ro, Songpa-gu, Seoul, Republi...",37.502686,127.092509
24,125,Gangdong-gu,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792

## 데이터 4) Measurement summary: 위의 세 가지 데이터를 기반으로 한 축약된 데이터 집합

아황산가스(ppm):SO2

이산화질소농도(ppm):NO2

오존농도(ppm):O3

일산화탄소농도(ppm):CO

미세먼지(㎍/㎥):PM10

초미세먼지(㎍/㎥):PM2.5

In [11]:
df= pd.read_csv('C:/jupyter notebook/data/Measurement_summary.csv',encoding='cp949')

In [12]:
df.shape

(647511, 11)

In [13]:
df.head()

,Measurement date,Station code,Address,Latitude,Longitude,SO2,NO2,O3,CO,PM10,PM2.5
0,2017-01-01 00:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,0.004,0.059,0.002,1.2,73.0,57.0
1,2017-01-01 01:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,0.004,0.058,0.002,1.2,71.0,59.0
2,2017-01-01 02:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,0.004,0.056,0.002,1.2,70.0,59.0
3,2017-01-01 03:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,0.004,0.056,0.002,1.2,70.0,58.0
4,2017-01-01 04:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,0.003,0.051,0.002,1.2,69.0,61.0

In [14]:
df.tail()

,Measurement date,Station code,Address,Latitude,Longitude,SO2,NO2,O3,CO,PM10,PM2.5
647506,2019-12-31 19:00,125,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792,0.003,0.028,0.013,0.5,23.0,17.0
647507,2019-12-31 20:00,125,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792,0.003,0.025,0.015,0.4,25.0,19.0
647508,2019-12-31 21:00,125,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792,0.003,0.023,0.015,0.4,24.0,17.0
647509,2019-12-31 22:00,125,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792,0.003,0.040,0.004,0.5,25.0,18.0
647510,2019-12-31 23:00,125,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792,0.003,0.037,0.005,0.5,27.0,18.0

In [15]:
df.isnull().sum()

Measurement date    0
Station code        0
Address             0
Latitude            0
Longitude           0
SO2                 0
NO2                 0
O3                  0
CO                  0
PM10                0
PM2.5               0
dtype: int64

In [16]:
df[['SO2', 'NO2', 'O3', 'CO', 'PM10', 'PM2.5']].describe()

,SO2,NO2,O3,CO,PM10,PM2.5
count,647511.000000,647511.000000,647511.000000,647511.000000,647511.000000,647511.000000
mean,-0.001795,0.022519,0.017979,0.509197,43.708051,25.411995
std,0.078832,0.115153,0.099308,0.405319,71.137342,43.924595
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,0.003000,0.016000,0.008000,0.300000,22.000000,11.000000
50%,0.004000,0.025000,0.021000,0.500000,35.000000,19.000000
75%,0.005000,0.038000,0.034000,0.600000,53.000000,31.000000
max,3.736000,38.445000,33.600000,71.700000,3586.000000,6256.000000

### 요약

어떤 경우에는 최소값이 -1이었음을 알 수 있다. 
측정 오류일 수 있으니, 최솟값이 -1인 발생 횟수를 확인해보기.

In [17]:
print("We have", df['SO2'].loc[(df['SO2']<0)].count(),"negative values for SO2")
print("We have", df['NO2'].loc[(df['NO2']<0)].count(),"negative values for NO2")
print("We have", df['O3'].loc[(df['O3']<0)].count(),"negative values for O3")
print("We have", df['CO'].loc[(df['CO']<0)].count(),"negative values for CO")
print("We have", df['PM10'].loc[(df['PM10']<0)].count(),"negative values for PM10")
print("We have", df['PM2.5'].loc[(df['PM2.5']<0)].count(),"negative values for PM2.5")

We have 3976 negative values for SO2
We have 3834 negative values for NO2
We have 4059 negative values for O3
We have 4036 negative values for CO
We have 3962 negative values for PM10
We have 3973 negative values for PM2.5

In [18]:
df['Measurement date'] = pd.to_datetime(df['Measurement date'])
print(df.shape)

(647511, 11)

In [20]:
data = df[df['SO2']<0]

In [21]:
data[['SO2','NO2','O3','CO','PM10','PM2.5']].describe()

          SO2          NO2           O3           CO         PM10        PM2.5
count  3976.0  3976.000000  3976.000000  3976.000000  3976.000000  3976.000000
mean     -1.0    -0.950757    -0.952024    -0.945800     3.472082     1.545020
std       0.0     0.219865     0.216616     0.242539    21.289433    15.424949
min      -1.0    -1.000000    -1.000000    -1.000000    -1.000000    -1.000000
25%      -1.0    -1.000000    -1.000000    -1.000000    -1.000000    -1.000000
50%      -1.0    -1.000000    -1.000000    -1.000000    -1.000000    -1.000000
75%      -1.0    -1.000000    -1.000000    -1.000000    -1.000000    -1.000000
max      -1.0     0.068000     0.059000     0.400000   561.000000   586.000000

### 정리

대부분의 컬럼에서 카운트가 같고 평균이 거의 -1에 가깝다는 것을 알 수 있기 때문에, 대부분이 같은 날짜에 발생하는 것으로 보인다.
이 값들을 평균으로 대체.

In [22]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=-1, strategy='mean')
df_imputed = pd.DataFrame(imp.fit_transform(df[["SO2","NO2","O3","CO","PM10","PM2.5"]]))
df_imputed.columns = df[["SO2","NO2","O3","CO","PM10","PM2.5"]].columns
df_imputed.index = df.index
remain_df = df[df.columns.difference(["SO2","NO2","O3","CO","PM10","PM2.5"])]
df_train = pd.concat([remain_df, df_imputed], axis=1)
df_train.head()

,Address,Latitude,Longitude,Measurement date,Station code,SO2,NO2,O3,CO,PM10,PM2.5
0,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,2017-01-01 00:00:00,101,0.004,0.059,0.002,1.2,73.0,57.0
1,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,2017-01-01 01:00:00,101,0.004,0.058,0.002,1.2,71.0,59.0
2,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,2017-01-01 02:00:00,101,0.004,0.056,0.002,1.2,70.0,59.0
3,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,2017-01-01 03:00:00,101,0.004,0.056,0.002,1.2,70.0,58.0
4,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,2017-01-01 04:00:00,101,0.003,0.051,0.002,1.2,69.0,61.0

In [24]:
last_entry = df.groupby('Station code').max()
last_entry

,Measurement date,Address,Latitude,Longitude,SO2,NO2,O3,CO,PM10,PM2.5
Station code,,,,,,,,,,
101,2019-12-31 23:00:00,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,0.406,0.109,0.325,40.0,516.0,513.0
102,2019-12-31 23:00:00,"15, Deoksugung-gil, Jung-gu, Seoul, Republic o...",37.564263,126.974676,0.082,0.248,0.178,8.7,296.0,276.0
103,2019-12-31 23:00:00,"136, Hannam-daero, Yongsan-gu, Seoul, Republic...",37.540033,127.004850,0.016,0.106,0.164,1.9,330.0,6256.0
104,2019-12-31 23:00:00,"215, Jinheung-ro, Eunpyeong-gu, Seoul, Republi...",37.609823,126.934848,0.080,0.121,0.186,8.0,985.0,985.0
105,2019-12-31 23:00:00,"32, Segeomjeong-ro 4-gil, Seodaemun-gu, Seoul,...",37.593742,126.949679,0.027,0.092,0.175,10.9,985.0,985.0
106,2019-12-31 23:00:00,"10, Poeun-ro 6-gil, Mapo-gu, Seoul, Republic o...",37.555580,126.905598,0.332,0.097,0.368,31.3,985.0,985.0
107,2019-12-31 23:00:00,"18, Ttukseom-ro 3-gil, Seongdong-gu, Seoul, Re...",37.541864,127.049659,0.144,0.113,0.189,15.3,985.0,985.0
108,2019-12-31 23:00:00,"571, Gwangnaru-ro, Gwangjin-gu, Seoul, Republi...",37.547180,127.092493,0.342,0.135,0.336,37.5,1661.0,985.0
109,2019-12-31 23:00:00,"43, Cheonho-daero 13-gil, Dongdaemun-gu, Seoul...",37.575743,127.028885,0.312,0.121,0.277,30.9,329.0,323.0
110,2019-12-31 23:00:00,"369, Yongmasan-ro, Jungnang-gu, Seoul, Republi...",37.584848,127.094023,0.223,0.087,0.271,22.3,693.0,660.0
111,2019-12-31 23:00:00,"70, Samyang-ro 2-gil, Seongbuk-gu, Seoul, Repu...",37.606719,127.027279,0.195,0.104,5.297,19.2,3403.0,995.0
112,2019-12-31 23:00:00,"49, Samyang-ro 139-gil, Gangbuk-gu, Seoul, Rep...",37.647930,127.011952,0.097,0.108,0.156,4.1,333.0,572.0
113,2019-12-31 23:00:00,"34, Sirubong-ro 2-gil, Dobong-gu, Seoul, Repub...",37.654192,127.029088,0.045,0.096,0.170,71.7,985.0,985.0
114,2019-12-31 23:00:00,"17, Sanggye-ro 23-gil, Nowon-gu, Seoul, Republ...",37.658774,127.068505,0.120,0.116,0.163,12.0,389.0,387.0
115,2019-12-31 23:00:00,"56, Jungang-ro 52-gil, Yangcheon-gu, Seoul, Re...",37.525939,126.856603,0.111,0.116,0.138,4.4,357.0,350.0
116,2019-12-31 23:00:00,"71, Gangseo-ro 45da-gil, Gangseo-gu, Seoul, Re...",37.544640,126.835151,0.233,0.111,1.009,2.5,3586.0,175.0
117,2019-12-31 23:00:00,"45, Gamasan-ro 27-gil, Guro-gu, Seoul, Republi...",37.498498,126.889692,3.736,38.445,33.600,26.2,1985.0,985.0
118,2019-12-31 23:00:00,"20, Geumha-ro 21-gil, Geumcheon-gu, Seoul, Rep...",37.452357,126.908296,0.115,0.110,0.155,4.6,695.0,724.0
119,2019-12-31 23:00:00,"11, Yangsan-ro 23-gil, Yeongdeungpo-gu, Seoul,...",37.525007,126.897371,0.254,0.310,0.498,25.6,985.0,985.0
120,2019-12-31 23:00:00,"6, Sadang-ro 16a-gil, Dongjak-gu, Seoul, Repub...",37.480917,126.971481,0.120,0.103,0.162,12.6,594.0,592.0
121,2019-12-31 23:00:00,"14, Sillimdong-gil, Gwanak-gu, Seoul, Republic...",37.487355,126.927102,0.365,0.117,0.404,36.8,2172.0,985.0
122,2019-12-31 23:00:00,"16, Sinbanpo-ro 15-gil, Seocho-gu, Seoul, Repu...",37.504547,126.994458,0.141,0.104,1.346,4.5,1985.0,985.0
123,2019-12-31 23:00:00,"426, Hakdong-ro, Gangnam-gu, Seoul, Republic o...",37.517528,127.047470,0.370,0.122,0.326,30.0,561.0,679.0
124,2019-12-31 23:00:00,"236, Baekjegobun-ro, Songpa-gu, Seoul, Republi...",37.502686,127.092509,0.176,0.114,0.170,17.2,985.0,985.0
125,2019-12-31 23:00:00,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792,0.378,0.113,0.332,36.7,622.0,610.0

In [26]:
def get_colors(data, df_item, item):
    item_row = df_item.loc[df_item['Item name'] == item]
    if (data > df_item.iloc[0]['Very bad(Red)']):
        return 'red'
    elif (data > df_item.iloc[0]['Bad(Yellow)']):
        return 'yellow'
    elif (data > df_item.iloc[0]['Normal(Green)']):
        return 'green'
    else:
        return 'blue'

In [27]:
last_entry['SO2 Color'] = last_entry['SO2'].apply(get_colors, args =(df_item, 'SO2' )) 
last_entry['NO2 Color'] = last_entry['NO2'].apply(get_colors, args =(df_item, 'NO2' )) 
last_entry['O3 Color'] = last_entry['O3'].apply(get_colors, args =(df_item, 'O3' )) 
last_entry['CO Color'] = last_entry['CO'].apply(get_colors, args =(df_item, 'CO' )) 
last_entry['PM10 Color'] = last_entry['PM10'].apply(get_colors, args =(df_item, 'PM10' )) 
last_entry['PM2.5 Color'] = last_entry['PM2.5'].apply(get_colors, args =(df_item, 'PM2.5' )) 
last_entry

,Measurement date,Address,Latitude,Longitude,SO2,NO2,O3,CO,PM10,PM2.5,SO2 Color,NO2 Color,O3 Color,CO Color,PM10 Color,PM2.5 Color
Station code,,,,,,,,,,,,,,,,
101,2019-12-31 23:00:00,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005007,0.406,0.109,0.325,40.0,516.0,513.0,yellow,green,yellow,red,red,red
102,2019-12-31 23:00:00,"15, Deoksugung-gil, Jung-gu, Seoul, Republic o...",37.564263,126.974676,0.082,0.248,0.178,8.7,296.0,276.0,green,yellow,yellow,red,red,red
103,2019-12-31 23:00:00,"136, Hannam-daero, Yongsan-gu, Seoul, Republic...",37.540033,127.004850,0.016,0.106,0.164,1.9,330.0,6256.0,blue,green,yellow,red,red,red
104,2019-12-31 23:00:00,"215, Jinheung-ro, Eunpyeong-gu, Seoul, Republi...",37.609823,126.934848,0.080,0.121,0.186,8.0,985.0,985.0,green,green,yellow,red,red,red
105,2019-12-31 23:00:00,"32, Segeomjeong-ro 4-gil, Seodaemun-gu, Seoul,...",37.593742,126.949679,0.027,0.092,0.175,10.9,985.0,985.0,blue,green,yellow,red,red,red
106,2019-12-31 23:00:00,"10, Poeun-ro 6-gil, Mapo-gu, Seoul, Republic o...",37.555580,126.905598,0.332,0.097,0.368,31.3,985.0,985.0,yellow,green,yellow,red,red,red
107,2019-12-31 23:00:00,"18, Ttukseom-ro 3-gil, Seongdong-gu, Seoul, Re...",37.541864,127.049659,0.144,0.113,0.189,15.3,985.0,985.0,green,green,yellow,red,red,red
108,2019-12-31 23:00:00,"571, Gwangnaru-ro, Gwangjin-gu, Seoul, Republi...",37.547180,127.092493,0.342,0.135,0.336,37.5,1661.0,985.0,yellow,green,yellow,red,red,red
109,2019-12-31 23:00:00,"43, Cheonho-daero 13-gil, Dongdaemun-gu, Seoul...",37.575743,127.028885,0.312,0.121,0.277,30.9,329.0,323.0,yellow,green,yellow,red,red,red
110,2019-12-31 23:00:00,"369, Yongmasan-ro, Jungnang-gu, Seoul, Republi...",37.584848,127.094023,0.223,0.087,0.271,22.3,693.0,660.0,yellow,green,yellow,red,red,red
111,2019-12-31 23:00:00,"70, Samyang-ro 2-gil, Seongbuk-gu, Seoul, Repu...",37.606719,127.027279,0.195,0.104,5.297,19.2,3403.0,995.0,yellow,green,red,red,red,red
112,2019-12-31 23:00:00,"49, Samyang-ro 139-gil, Gangbuk-gu, Seoul, Rep...",37.647930,127.011952,0.097,0.108,0.156,4.1,333.0,572.0,green,green,yellow,red,red,red
113,2019-12-31 23:00:00,"34, Sirubong-ro 2-gil, Dobong-gu, Seoul, Repub...",37.654192,127.029088,0.045,0.096,0.170,71.7,985.0,985.0,blue,green,yellow,red,red,red
114,2019-12-31 23:00:00,"17, Sanggye-ro 23-gil, Nowon-gu, Seoul, Republ...",37.658774,127.068505,0.120,0.116,0.163,12.0,389.0,387.0,green,green,yellow,red,red,red
115,2019-12-31 23:00:00,"56, Jungang-ro 52-gil, Yangcheon-gu, Seoul, Re...",37.525939,126.856603,0.111,0.116,0.138,4.4,357.0,350.0,green,green,green,red,red,red
116,2019-12-31 23:00:00,"71, Gangseo-ro 45da-gil, Gangseo-gu, Seoul, Re...",37.544640,126.835151,0.233,0.111,1.009,2.5,3586.0,175.0,yellow,green,red,red,red,red
117,2019-12-31 23:00:00,"45, Gamasan-ro 27-gil, Guro-gu, Seoul, Republi...",37.498498,126.889692,3.736,38.445,33.600,26.2,1985.0,985.0,red,red,red,red,red,red
118,2019-12-31 23:00:00,"20, Geumha-ro 21-gil, Geumcheon-gu, Seoul, Rep...",37.452357,126.908296,0.115,0.110,0.155,4.6,695.0,724.0,green,green,yellow,red,red,red
119,2019-12-31 23:00:00,"11, Yangsan-ro 23-gil, Yeongdeungpo-gu, Seoul,...",37.525007,126.897371,0.254,0.310,0.498,25.6,985.0,985.0,yellow,yellow,yellow,red,red,red
120,2019-12-31 23:00:00,"6, Sadang-ro 16a-gil, Dongjak-gu, Seoul, Repub...",37.480917,126.971481,0.120,0.103,0.162,12.6,594.0,592.0,green,green,yellow,red,red,red
121,2019-12-31 23:00:00,"14, Sillimdong-gil, Gwanak-gu, Seoul, Republic...",37.487355,126.927102,0.365,0.117,0.404,36.8,2172.0,985.0,yellow,green,yellow,red,red,red
122,2019-12-31 23:00:00,"16, Sinbanpo-ro 15-gil, Seocho-gu, Seoul, Repu...",37.504547,126.994458,0.141,0.104,1.346,4.5,1985.0,985.0,green,green,red,red,red,red
123,2019-12-31 23:00:00,"426, Hakdong-ro, Gangnam-gu, Seoul, Republic o...",37.517528,127.047470,0.370,0.122,0.326,30.0,561.0,679.0,yellow,green,yellow,red,red,red
124,2019-12-31 23:00:00,"236, Baekjegobun-ro, Songpa-gu, Seoul, Republi...",37.502686,127.092509,0.176,0.114,0.170,17.2,985.0,985.0,yellow,green,yellow,red,red,red
125,2019-12-31 23:00:00,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792,0.378,0.113,0.332,36.7,622.0,610.0,yellow,green,yellow,red,red,red

In [29]:
!pip install folium

Collecting folium
  Downloading folium-0.11.0-py2.py3-none-any.whl (93 kB)
Requirement already satisfied: numpy in c:\anaconda\envs\song\lib\site-packages (from folium) (1.18.1)
Collecting branca>=0.3.0
  Downloading branca-0.4.1-py3-none-any.whl (24 kB)
Requirement already satisfied: requests in c:\anaconda\envs\song\lib\site-packages (from folium) (2.23.0)
Requirement already satisfied: jinja2>=2.9 in c:\anaconda\envs\song\lib\site-packages (from folium) (2.11.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda\envs\song\lib\site-packages (from requests->folium) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\anaconda\envs\song\lib\site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\anaconda\envs\song\lib\site-packages (from requests->folium) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\anaconda\envs\song\lib\site-packages (from requests->folium) (1.25.8)
Requirement already satisfied: MarkupSafe>=0.23 in c:\anaconda\envs\song\lib\site-packages (from jinja2>=2.9->folium) (1.1.1)
Installing collected packages: branca, folium
Successfully installed branca-0.4.1 folium-0.11.0

In [33]:
import folium as folium

In [34]:
# This creates the map object
m = folium.Map(
    location=[37.541, 126.981], # center of where the map initializes
    #tiles='Stamen Toner', # the style used for the map (defaults to OSM)
    zoom_start=11, # the initial zoom level
    title = "Pollution level of SO2") 
for ind in last_entry.index: 
    #print(row[1][0])
    folium.Marker([last_entry['Latitude'][ind], last_entry['Longitude'][ind]], popup=ind, icon=folium.Icon(color=last_entry['SO2 Color'][ind], icon='info-sign')).add_to(m)

In [35]:
# Diplay the map
m